### ISSUE TITLE
Add contribution instructions to the README.

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/fvm-docs#13]
This is kinda future-proofing, but we're going to need to add instructions on how and where to add individual pages to this repo - this'll help unblock writers outside of the docs team who want to add content.

## Tasks

- [ ] How to add a new page.
- [ ] How to add images.
- [ ] How `relref` links work.
- [ ] How to test the site locally.
- [ ] How to add items to the sidebar.
    - [ ] Make a note that this should only be done by the docs team, so things don't break.
- [ ] Warn folks to stay out of all folders except `content`, so things don't break.

**Comment by johnnymatthews** [comment]
Blocked by #60.
