### ISSUE TITLE
Create a README for this project.

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/fvm-docs#33]
This project needs a good readme. Use https://github.com/othneildrew/Best-README-Template/blob/master/BLANK_README.md as a guide.

## Tasks

- [x] Copy https://github.com/othneildrew/Best-README-Template/blob/master/BLANK_README.md
- [x] Remove unnecessary status icons.
- [x] Replace logo with FVM logo.
- [x] Add a screenshot of the FVM Docs homepage.
- [x] Update the **Built with** section to include, Hugo, GetDoks, and Fleek.
- [x] Rename the **Getting started** section to **Run locally**.
    - [x] Add the steps to get this project build and run locally.
- [x] Remove the **Usage** section.
- [x] Remove the **Roadmap** section.
- [x] Remove the **Acknowledgements** section.

**Comment by johnnymatthews** [comment]
Closed in https://github.com/filecoin-project/fvm-docs/commit/3a5738e01a936b601f591262d3e3caa351351f36
